name: Docker

on:
  push:
    branches: [ master, release/*, gr-main* ]
    tags: [ '**' ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ghcr.io
      IMAGE_NAME: ${{ github.repository_owner }}/alerta-api
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.REPOSITORY_URL }}
      - name: Build image
        id: docker-build
        run: >-
          docker build
          -t $IMAGE_NAME
          -t ${{ steps.string.outputs.lowercase }}/$IMAGE_NAME:$(cat VERSION)
          -t ${{ steps.string.outputs.lowercase }}/$IMAGE_NAME:$(git rev-parse --short HEAD)
          -t ${{ steps.string.outputs.lowercase }}/$IMAGE_NAME:latest .
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REPOSITORY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Image
        id: docker-push
        run: docker push --all-tags ${{ steps.string.outputs.lowercase }}/$IMAGE_NAME

      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
